# Generated by Django 4.0.1 on 2022-01-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cold_start',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(max_length=1)),
                ('Thrillers', models.IntegerField(verbose_name=2)),
                ('Romance', models.IntegerField(verbose_name=2)),
                ('Nonfiction', models.IntegerField(verbose_name=2)),
                ('Humor', models.IntegerField(verbose_name=2)),
                ('Horror', models.IntegerField(verbose_name=2)),
            ],
        ),
        migrations.CreateModel(
            name='recommender_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(max_length=200)),
                ('BookTitle', models.CharField(max_length=200)),
                ('BookRating', models.IntegerField(max_length=200)),
            ],
        ),
    ]
