# Generated by Django 4.0.1 on 2022-01-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cold_start',
            name='Horror',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cold_start',
            name='Humor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cold_start',
            name='Nonfiction',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cold_start',
            name='Romance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cold_start',
            name='Thrillers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cold_start',
            name='UserID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recommender_book',
            name='BookRating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recommender_book',
            name='UserID',
            field=models.IntegerField(),
        ),
    ]
